/* Brand assets — the real MDG Services logo.
   PNGs live in /public and are generated by scripts/gen-logos.mjs
   (black variants for light surfaces, white variants for navy ones). */

export function LogoFull({ className }: { className?: string }) {
  return <img src="/logo-full.png" alt="MDG Services" className={className} draggable={false} />;
}

export function LogoFullWhite({ className }: { className?: string }) {
  return <img src="/logo-full-white.png" alt="MDG Services" className={className} draggable={false} />;
}

export function LogoMark({
  white = false,
  className,
  alt = "MDG Services",
}: {
  white?: boolean;
  className?: string;
  alt?: string;
}) {
  return (
    <img
      src={white ? "/logo-mark-white.png" : "/logo-mark.png"}
      alt={alt}
      className={className}
      draggable={false}
    />
  );
}
